# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('queuePosition', models.IntegerField(default=-1)),
                ('storeId', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('comment', models.CharField(max_length=256)),
                ('rating', models.CharField(max_length=256)),
                ('albumArtRef', models.CharField(max_length=1024)),
                ('artistId', models.CharField(max_length=256)),
                ('composer', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('creationTimestamp', models.CharField(max_length=256)),
                ('album', models.CharField(max_length=256)),
                ('totalDiscCount', models.IntegerField(default=0)),
                ('recentTimestamp', models.CharField(max_length=256)),
                ('albumArtist', models.CharField(max_length=256)),
                ('trackNumber', models.IntegerField()),
                ('discNumber', models.IntegerField()),
                ('deleted', models.BooleanField()),
                ('nid', models.CharField(max_length=256)),
                ('totalTrackCount', models.IntegerField(default=0)),
                ('estimatedSize', models.CharField(max_length=256)),
                ('albumId', models.CharField(max_length=256)),
                ('beatsPerMinute', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=256)),
                ('playCount', models.IntegerField()),
                ('artistArtRef', models.CharField(max_length=1024)),
                ('kind', models.CharField(max_length=256)),
                ('artist', models.CharField(max_length=256)),
                ('lastModifiedTimestamp', models.CharField(max_length=256)),
                ('clientId', models.CharField(max_length=256)),
                ('durationMillis', models.CharField(max_length=256)),
            ],
        ),
    ]
