# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackQueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='discNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='playCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='trackNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
