# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackQueue', '0002_auto_20170630_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='id',
            field=models.CharField(default=-1, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='storeId',
            field=models.CharField(max_length=256),
        ),
    ]
